on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
    
      - name: Pull Vertica CE image
        run: docker pull vertica/vertica-ce:11.1.1-0
    
      - name: Start Vertica CE container
        run: docker run -d -p 5433:5433 --name vertica vertica/vertica-ce:11.1.1-0

      - name: ping
        run: |
          for i in {0..60}
            if [[ docker exec vertica /opt/vertica/bin/admintools -t db_status -s UP == "*VMart*" ]]; then
              break
            sleep 1
            fi
          done
    
      - name: Wait for Vertica CE to start
        run: docker exec vertica /opt/vertica/bin/admintools -t view_cluster -x

      - name: Connect to db
        run: docker exec vertica /opt/vertica/bin/vsql -h localhost -U dbadmin -d VMart -c "select 1"
    
      - name: Run Python script to test connection
        run: |
          pip3 install psycopg2
          python3 << EOF
          import psycopg2
    
          # Connect to Vertica
          conn = psycopg2.connect(host='localhost', port=5433, database='VMart', user='dbadmin')
          conn.set_client_encoding('UTF8')
    
          # Create a cursor
          cur = conn.cursor()
    
          # Execute a SQL query
          cur.execute('SELECT 1')
    
          # Fetch the results
          row = cur.fetchone()
    
          # Close the cursor and connection
          cur.close()
          conn.close()
    
          # Print the result
          print(row)
          EOF
    
      - name: Stop Vertica CE container
        run: docker stop vertica
