on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
    
      - name: Pull Vertica CE image
        run: docker pull vertica/vertica-ce:11.1.1-0
    
      - name: Start Vertica CE container
        run: docker run -d --name vertica vertica/vertica-ce:11.1.1-0
    
      - name: Wait for Vertica CE to start
        run: docker exec vertica /opt/vertica/bin/admintools -t view_cluster
    
      - name: Run Python script to test connection
        run: |
          python3 << EOF
          import psycopg2
    
          # Connect to Vertica
          conn = psycopg2.connect(host='localhost', port=5433, database='VMart', user='dbadmin')
    
          # Create a cursor
          cur = conn.cursor()
    
          # Execute a SQL query
          cur.execute('SELECT 1')
    
          # Fetch the results
          row = cur.fetchone()
    
          # Close the cursor and connection
          cur.close()
          conn.close()
    
          # Print the result
          print(row)
          EOF
    
      - name: Stop Vertica CE container
        run: docker stop vertica
