on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
          # Label used to access the service container
          vertica:
            # Docker Hub image
            image: vertica/vertica-ce:latest
            ports:
              - 5433:5433
              - 5444:5444
            options: >-
              --health-cmd "/opt/vertica/bin/admintools -t db_status -s UP | grep docker"
              --health-interval 2s
              --health-timeout 5s
              --health-retries 30
            env:
              VERTICA_MEMDEBUG: 2
              VERTICA_DB_NAME: docker
              VMART_ETL_SCRIPT: ''
              VMART_ETL_SQL: ''
    steps:
      - uses: actions/checkout@v3
    
      - name: Run Python script to test connection
        run: |
          pip3 install psycopg2
          python3 << EOF
          import psycopg2
    
          # Connect to Vertica
          conn = psycopg2.connect(host='localhost', port=5433, database='docker', user='dbadmin')
          conn.set_client_encoding('UTF8')
    
          # Create a cursor
          cur = conn.cursor()
    
          # Execute a SQL query
          cur.execute('SELECT 1')
    
          # Fetch the results
          row = cur.fetchone()
    
          # Close the cursor and connection
          cur.close()
          conn.close()
    
          # Print the result
          print(row)
          EOF
